openapi: "3.0.2"
info:
  title: Mercado Pago
  version: "1.0"
servers:
  - url: http://localhost/mercadopago/
paths:
  /findUserAccount/{userId}:
    get:
      summary: Find an account for a redistered user
      parameters:
        - name: userId
          in: path
          required: true
          description: id of the user
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int64
        '404':
          description: A user with the specified ID was not found.
  /buyCredits:
    post:
      summary: Buy credits in Mercado Pago
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyCredits'
      responses:
        '200':
          description: Operation success
        '404':
          description: Account not found
components:
  schemas:
    BuyCredits:
      type: object
      properties:
        mercadoPagoAccountId:
          type: integer
          format: int32
        credits:
          type: number
          format: double
